package com.hexing.fdmdemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hexing.fdmdemo.db.DBTest;
import com.hexing.fdmdemo.db.UserInfo;

import com.hexing.fdmdemo.db.DBTestDao;
import com.hexing.fdmdemo.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBTestDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final DBTestDao dBTestDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBTestDaoConfig = daoConfigMap.get(DBTestDao.class).clone();
        dBTestDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        dBTestDao = new DBTestDao(dBTestDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(DBTest.class, dBTestDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        dBTestDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public DBTestDao getDBTestDao() {
        return dBTestDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
